project:
  type: book
  output-dir: docs

book:
  title: "Structural equation modeling with R cookbook"
  author: "Deon de Bruin"
  date: "2025/01/20"
  chapters:
    - index.qmd
    - intro.qmd
    - Spearman.qmd
    - Multiple_factors.qmd
    - Modification_indices.qmd
    - EFA.qmd
    - Correlated_residuals.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

