project:
  type: book
  output-dir: docs

book:
  title: "Structural equation modeling with lavaan in R: Examples and excercises"
  author: "Deon de Bruin"
  date: "2025/01/20"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part I: Introduction to R"
    - Vectors_dataframes.qmd
    - ReadingStoringData.qmd
    - DataManagement.qmd
    - Subsetting.qmd
    - part: "Part II: Measurement model"
    - Estimating_correlations.qmd
    - Spearman.qmd
    - Measurement_models.qmd
    - Multiple_factors.qmd
    - Higher_order.qmd
    - Plotting_models.qmd
    - Measurement_invariance.qmd
    - MIMIC Models.qmd
    - Ordinal.qmd
    - part: "Part III: Diagnosing and improving the measurement model"
    - Modification_indices.qmd
    - EFA.qmd
    - Correlated_residuals.qmd
    - part: "Part IV: Structural model"
    - MissingDataExamples.qmd
    - Mediation.qmd
    - Moderation.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

