project:
  type: book
  output-dir: docs

book:
  title: "Structural equation modeling with lavaan in R: Examples and excercises"
  author: "Deon de Bruin"
  date: "2025/01/20"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part I: Measurement model"
    - Spearman.qmd
    - Multiple_factors.qmd
    - part: "Part II: Diagnosing and improving the measurement model"
    - Modification_indices.qmd
    - EFA.qmd
    - Correlated_residuals.qmd
    - part: "Part III: Structural model"
    - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

